apiVersion: batch/v1
kind: CronJob
metadata:
  name: euro-cronjob
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: euro
            image: meu-euro:latest
          restartPolicy: OnFailure

