apiVersion: batch/v1
kind: CronJob
metadata:
  name: dolar-cronjob
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dolar
            image: meu-dolar:latest
          restartPolicy: OnFailure

